In [1]:
import pandas as pd

In [2]:
#path for preprocessed csv
data = pd.read_csv('../../preprocessed.csv')

In [3]:
data

,text,summary
0,the daman and diu administration on wednesday ...,the administration of union territory daman an...
1,"from her special numbers to tv?appearances, bo...",malaika arora slammed an instagram user who tr...
2,the indira gandhi institute of medical science...,the indira gandhi institute of medical science...
3,lashkar-e-taiba's kashmir commander abu dujana...,lashkar-e-taiba's kashmir commander abu dujana...
4,hotels in mumbai and other indian cities are t...,hotels in maharashtra will train their staff t...
...,...,...
4391,"mumbai, feb (pti) fruit juice concentrate m...",fruit juice concentrate maker rasna is eyeing ...
4392,former cricketer sachin tendulkar was spotted ...,former indian cricketer sachin tendulkar atten...
4393,"aamir khan, whose last film dangal told the st...","aamir khan, while talking about reality shows ..."
4394,maharahstra power minister chandrashekhar bawa...,the maharashtra government has initiated an in...
4395,more than half of the languages spoken by indi...,at least languages or more than half langu...

In [4]:
# remove stopwords from text and summary columns
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Perplex420\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
# function to remove stopwords
def remove_stopwords(text):
    text = ' '.join([word for word in text.split() if word not in (stop)])
    return text

#apply remove_stopwords function to text and summary columns
data['text'] = data['text'].apply(lambda x: remove_stopwords(x))

data['summary'] = data['summary'].apply(lambda x: remove_stopwords(x))

data

,text,summary
0,daman diu administration wednesday withdrew ci...,administration union territory daman diu revok...
1,"special numbers tv?appearances, bollywood acto...","malaika arora slammed instagram user trolled ""..."
2,indira gandhi institute medical sciences (igim...,indira gandhi institute medical sciences (igim...
3,lashkar-e-taiba's kashmir commander abu dujana...,lashkar-e-taiba's kashmir commander abu dujana...
4,hotels mumbai indian cities train staff spot s...,hotels maharashtra train staff spot signs sex ...
...,...,...
4391,"mumbai, feb (pti) fruit juice concentrate make...",fruit juice concentrate maker rasna eyeing rev...
4392,former cricketer sachin tendulkar spotted rajy...,former indian cricketer sachin tendulkar atten...
4393,"aamir khan, whose last film dangal told story ...","aamir khan, talking reality shows television f..."
4394,maharahstra power minister chandrashekhar bawa...,maharashtra government initiated inquiry -year...
4395,half languages spoken india's . billion people...,least languages half languages spoken india's ...

In [6]:
# clean text and summary columns

import re

def clean_text(text):
    # remove numbers
    text = re.sub(r'\([^)]*\)', '', text)
    # remove punctuations and special characters
    text = re.sub('"','', text)
    
    text = ' '.join(text.split())
    return text

data['text'] = data['text'].apply(lambda x: clean_text(x))

data['summary'] = data['summary'].apply(lambda x: clean_text(x))

data

,text,summary
0,daman diu administration wednesday withdrew ci...,administration union territory daman diu revok...
1,"special numbers tv?appearances, bollywood acto...",malaika arora slammed instagram user trolled d...
2,indira gandhi institute medical sciences patna...,indira gandhi institute medical sciences patna...
3,lashkar-e-taiba's kashmir commander abu dujana...,lashkar-e-taiba's kashmir commander abu dujana...
4,hotels mumbai indian cities train staff spot s...,hotels maharashtra train staff spot signs sex ...
...,...,...
4391,"mumbai, feb fruit juice concentrate maker rasn...",fruit juice concentrate maker rasna eyeing rev...
4392,former cricketer sachin tendulkar spotted rajy...,former indian cricketer sachin tendulkar atten...
4393,"aamir khan, whose last film dangal told story ...","aamir khan, talking reality shows television f..."
4394,maharahstra power minister chandrashekhar bawa...,maharashtra government initiated inquiry -year...
4395,half languages spoken india's . billion people...,least languages half languages spoken india's ...

In [7]:
#save cleaned data to csv

data.to_csv('data.csv', index=False)